kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
